name: pryvee

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.2
  flutter_native_splash: ^2.2.7
  curved_navigation_bar: ^1.0.3
  google_maps_flutter: ^2.1.12
  shared_preferences: ^2.0.15
  time_ago_provider: ^4.1.2
  contacts_service: ^0.6.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  share_extend: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.3
  collection: ^1.16.0
  geolocator: ^9.0.1
  provider: ^6.0.3
  shimmer: ^2.0.0
  rxdart: ^0.27.5
  get_it: ^7.2.0
  intl: ^0.17.0
  http: ^0.13.5
  dio: ^4.0.6
  firebase_storage: ^11.0.3
  permission_handler: ^10.2.0
  awesome_notifications: ^0.6.13
  flutter_screenutil: ^5.6.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: img/splash-screen.png
  color: "#E63946"
  fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - img/
    - languages-json/
    - map-style/

  fonts:
    - family: PryveeIconFont
      fonts:
        - asset: fonts/PryveeIconFont.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: fonts/Nunito-Light.ttf
          weight: 200
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Medium.ttf
          weight: 600
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 800
        - asset: fonts/Nunito-Bold.ttf
          weight: 900
